### ISSUE TITLE
Support collection of JMX composite metric types with CollectD FastJMX 

### ISSUE THREAD

**Issue by cristinanegrean** [mevdschee/tqdev-metrics#12]
Having bellow CollectD java plugin configuration:

`<MBean "xls_tasks">
      ObjectName "com.xebialabs.satellite.metrics:type=Metrics"

     <Value>
        Type "gauge"
        InstancePrefix "xls_registered_tasks"
        PluginName "XLS"
        Attribute "xlsatellite.Tasks.registered"
      </Value>
      <Value>
        Type "gauge"
        InstancePrefix "xls_executing_tasks"
        PluginName "XLS"
        Attribute "xlsatellite.Tasks.executing"
      </Value>
      <Value>
        Type "counter"
        InstancePrefix "xls-done_tasks"
        PluginName "XLS"
        Attribute "xlsatellite.Tasks.done"
      </Value>
 
    </MBean>`

and above metrics exposed via JMX
<img width="990" alt="screen shot 2018-05-31 at 10 20 32" src="https://user-images.githubusercontent.com/5502867/40771519-d791dd16-64bd-11e8-8963-556ff1179533.png">

CollectD FastJMX plugin reports below error:

[2018-05-31 10:24:07] FastJMX Plugin: Failed to collect: javax.management.RuntimeOperationsException: Operation xlsatellite not defined for this OpenMBean

From the error message it looks like the JMXReporter#getAttribute(String attributeName) can not handle attribute paths: "xlsatellite.Tasks.done", "xlsatellite.Tasks.running", ""xlsatellite.Tasks.executing",  but only attribute names. 

From the docs of CollectD: 

"Attribute path
Sets the name of the attribute from which to read the value. You can access the keys of composite types by using a dot to concatenate the key name to the attribute name. For example: “attrib0.key42”. If Table is set to true path must point to a composite type, otherwise it must point to a numeric type."

we should be able to support lookup of not only "attrib0", but also of "attrib0.key42", as well as resolution of simple numeric type: collectD type gauge or counter.

**Comment by mevdschee** [comment]
Great find. Do you think getAttribute is called with "xlsatellite.Tasks.done" as "String attributeName" parameter? In that case implementing such path traversal should be done here:

https://github.com/mevdschee/tqdev-metrics/blob/master/metrics-jmx/src/main/java/com/tqdev/metrics/jmx/JmxReporter.java#L102

Splitting this attribute on the last '.' should then should make the distinction between key and value. I'm not in the situation to make a test case for this now. Could you do a PR?

**Comment by cristinanegrean** [comment]
Thanks for the hint and double check Maurits. I've pinpointed the same code. Will submit a PR for it today.
